### ISSUE TITLE
Support `afterAll` hooks

### ISSUE THREAD

**Issue by ksmith27** [Tyler-Murphy/parallel-test#1]
From the readme:

> helpers for beforeAll, afterAll, beforeEach, afterEach. They might be implemented as functions that accept test and a callback, and returns a modified version of test that will run the hooks. There could be a separate function for each one, or a single addHooks function that accepts multiple hooks

**Comment by Tyler-Murphy** [comment]
Closed by f1b21a4ee8beeedeaa85da3cdadaab362e602ef2, which adds an event emitter that emits an event when the test suite is done running.

Now that the emitter is there, it could be used to emit other events, too.
